### ISSUE TITLE
D2Net  pretrain model provided?

### ISSUE THREAD

**Issue by luluka2** [shangwei5/D2Net#1]
Hi, it's a good job!
would you please provide the D2Net  pretrain model?

Thanks

**Comment by shangwei5** [comment]
Thank you for your attention to our work！
We have provided the model trained on our GOPRO_Random dataset, you can download in Readme.

Thanks

**Comment by luluka2** [comment]
The download link is ok.

Thanks

> Thank you for your attention to our work！ We have provided the model trained on our GOPRO_Random dataset, you can download in Readme.
> 
> Thanks
