### ISSUE TITLE
Problem when training main_d2net_event.py: ValueError: not enough values to unpack (expected 5, got 4)

### ISSUE THREAD

**Issue by tlwzzy** [shangwei5/D2Net#3]
Some outputs: when i execute python main_d2net_event.py: 
=========================================================================
DataSet INPUT path: /home/featurize/data/event_deblur/test/blur
DataSet label path: /home/featurize/data/event_deblur/test/label
Number of videos to load: 11
Number of frames to load: 1633
Using Trainer-D2Net
Now training
/environment/miniconda3/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:134: UserWarning: Detected call of `lr_scheduler.step()` before `optimizer.step()`. In PyTorch 1.1.0 and later, you should call them in the opposite order: `optimizer.step()` before `lr_scheduler.step()`.  Failure to do this will result in PyTorch skipping the first value of the learning rate schedule. See more details at https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate
  "https://pytorch.org/docs/stable/optim.html#how-to-adjust-learning-rate", UserWarning)
/environment/miniconda3/lib/python3.7/site-packages/torch/optim/lr_scheduler.py:370: UserWarning: To get the last learning rate computed by the scheduler, please use `get_last_lr()`.
  "please use `get_last_lr()`.", UserWarning)
Epoch   1 with Lr 1.00e-4
Traceback (most recent call last):
  File "main_d2net_event.py", line 21, in <module>
    t.train()
  File "/home/featurize/work/D2Net/code/trainer/trainer_d2net_event.py", line 36, in train
    for batch, (input, gt, event, label, _) in enumerate(self.loader_train):
  ValueError: not enough values to unpack (expected 5, got 4)
===============================================================================
but when i try main_d2net.py, I can train it good. So I guess there's something wrong in event_d2net's dataloader?

**Comment by shangwei5** [comment]
You may not change the template in option/_init_.py, or try to run "python main_xx.py --template D2NET_EVENT "

**Comment by tlwzzy** [comment]
> You may not change the template in option/_init_.py, or try to run "python main_xx.py --template D2NET_EVENT "

Thanks for the answer that resolved my problem.
