### ISSUE TITLE
Questions about BiLSTM detector

### ISSUE THREAD

**Issue by HaoDot** [shangwei5/D2Net#6]
Hi @shangwei5 , sorry to disturb you again. I have some questions remaining. Could you offer me some explanations?
- Q1: how to use events as input in BiLSTM detector?
As shown in [here](https://github.com/shangwei5/D2Net/blob/main/code/model/BiLSTM_test.py#L46), the first conv layer has 3 channels, which seems that it is designed for RGB frame. However, `BiLSTM_resnet152` has [a 20-channel-input conv layer](https://github.com/shangwei5/D2Net/blob/main/code/model/BiLSTM_test.py#L24), I wonder if I could use this layer to take event as input.
- Q2: the representation of events in BiLSTM detector
It seems that the [representation code](https://github.com/shangwei5/D2Net/blob/main/code/data/event_txt2npy.py#L19) that you offered has 40 channels. I am not sure if it is the representation for **Event-BiLSTM detector**.
Thanks for your time.

**Comment by shangwei5** [comment]
We have updated the code before. The current one only supports the detection of RGB frames. 
self.conv_e in  BiLSTM_resnet152 is not used.

**Comment by HaoDot** [comment]
Thanks for your reply! I have looked through the [commit history](https://github.com/shangwei5/D2Net/commits/main), but I didn't find the code that you mentioned. I wonder if you could help me to point it out. Certainly, it's totally fine for me to put it aside.
Thanks for your help!

**Comment by shangwei5** [comment]
Please see this link: https://pan.baidu.com/s/16skQhOc5gpe-jE0FvwIXbA(password:thv5)
It contains old version of BiLSTM detector and pretrained model (with event or img),  but I find the pretrained model in the backup file. I‘m not sure whether it matches the model file(BiLSTM.py).

**Comment by HaoDot** [comment]
Thx for your help!
Both img-based BiLSTM and event-based one matches its corresponding weight! 
The last question for me is the representation for input events, in event-based BiLSTM, which needs 20-channel input. I am not sure whether I can used [this code](https://github.com/shangwei5/D2Net/blob/main/code/data/event_txt2npy.py#L19) by simply setting to 20 channels?
Thanks for your time again!

**Comment by shangwei5** [comment]
you need also change the flowing code(e.g., frame idx into 10), the total number of channels contains positive and negative polarity. That means if you change total channel into 20, you should also change line 20,26,27,36,37 in [this code](https://github.com/shangwei5/D2Net/blob/main/code/data/event_txt2npy.py).

**Comment by HaoDot** [comment]
Got it! Thx for your time
